# NumPy
Es una librería para el manejo de datos, que convierte a Python en un lenguaje de programación muy potente, equivalente a MATLAB en el manejo de matrices numéricas. Lo primero que se tiene que hacer es importar nuestra librería con el siguiente comando:

In [11]:
import numpy as np
import math

In [4]:
L = [1, 2, 3, 4, 5] # crear una lista
x1 = np.array(L, dtype = 'float32')
x1

array([1., 2., 3., 4., 5.], dtype=float32)

## Tipos de datos de NumPy
- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_, float16, float32, float64
- complex_, complex64, complex128 (a,bi a, b $\in$ float_)

In [6]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3, 12, dtype= np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
np.arange(4, 5, 0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [14]:
np.linspace(0, 6*math.pi, 50)

array([ 0.        ,  0.38468481,  0.76936963,  1.15405444,  1.53873926,
        1.92342407,  2.30810889,  2.6927937 ,  3.07747852,  3.46216333,
        3.84684815,  4.23153296,  4.61621778,  5.00090259,  5.38558741,
        5.77027222,  6.15495704,  6.53964185,  6.92432667,  7.30901148,
        7.69369629,  8.07838111,  8.46306592,  8.84775074,  9.23243555,
        9.61712037, 10.00180518, 10.38649   , 10.77117481, 11.15585963,
       11.54054444, 11.92522926, 12.30991407, 12.69459889, 13.0792837 ,
       13.46396852, 13.84865333, 14.23333814, 14.61802296, 15.00270777,
       15.38739259, 15.7720774 , 16.15676222, 16.54144703, 16.92613185,
       17.31081666, 17.69550148, 18.08018629, 18.46487111, 18.84955592])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
x.reshape((6, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
x.reshape((3, 8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [21]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.ravel(x) # Ordenado en un solo vector

array([1, 2, 3, 4, 5, 6])

In [25]:
x.flatten() #Una copia

array([1, 2, 3, 4, 5, 6])

In [26]:
np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
np.resize(x, (3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

### Ejercicios
1. Crear un array de datos con valores entre 5 y 120.
2. Crear una matriz 4x4 con los valores desde 0 hasta 15.
3. Crear la identidad 7x7.
4. Crear un array de 20 elementos y transformarlo en una matriz de 5x4.
5. Crar un array con 20 números con los valores entre 0 y 5 espacioados uniformemente.

In [36]:
x = np.arange(5, 120)
x

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [39]:
x1 = np.arange(16)
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
matriz1 = x1.reshape((4, 4))

In [41]:
matriz1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
identidad = np.ones((7, 7))

In [47]:
identidad

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [48]:
x2 = np.arange(20)
matriz2 = x2.reshape((5, 4))

In [49]:
matriz2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [50]:
lin = np.linspace(0, 5, 20)

In [51]:
lin

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [52]:
len(lin)

20

**Tareas concluidas**