# NumPy
Es una librería para el manejo de datos, que convierte a Python en un lenguaje de programación muy potente, equivalente a MATLAB en el manejo de matrices numéricas. Lo primero que se tiene que hacer es importar nuestra librería con el siguiente comando:

In [2]:
import numpy as np
import math

In [4]:
L = [1, 2, 3, 4, 5] # crear una lista
x1 = np.array(L, dtype = 'float32')
x1

array([1., 2., 3., 4., 5.], dtype=float32)

## Tipos de datos de NumPy
- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8, uint16, uint32, uint64
- float_, float16, float32, float64
- complex_, complex64, complex128 (a,bi a, b $\in$ float_)

In [6]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3, 12, dtype= np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
np.arange(4, 5, 0.1)

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [14]:
np.linspace(0, 6*math.pi, 50)

array([ 0.        ,  0.38468481,  0.76936963,  1.15405444,  1.53873926,
        1.92342407,  2.30810889,  2.6927937 ,  3.07747852,  3.46216333,
        3.84684815,  4.23153296,  4.61621778,  5.00090259,  5.38558741,
        5.77027222,  6.15495704,  6.53964185,  6.92432667,  7.30901148,
        7.69369629,  8.07838111,  8.46306592,  8.84775074,  9.23243555,
        9.61712037, 10.00180518, 10.38649   , 10.77117481, 11.15585963,
       11.54054444, 11.92522926, 12.30991407, 12.69459889, 13.0792837 ,
       13.46396852, 13.84865333, 14.23333814, 14.61802296, 15.00270777,
       15.38739259, 15.7720774 , 16.15676222, 16.54144703, 16.92613185,
       17.31081666, 17.69550148, 18.08018629, 18.46487111, 18.84955592])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
x = np.arange(24)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [17]:
x.reshape((6, 4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
x.reshape((3, 8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [21]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.ravel(x) # Ordenado en un solo vector

array([1, 2, 3, 4, 5, 6])

In [25]:
x.flatten() #Una copia

array([1, 2, 3, 4, 5, 6])

In [26]:
np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
np.resize(x, (3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

### Ejercicios
1. Crear un array de datos con valores entre 5 y 120.
2. Crear una matriz 4x4 con los valores desde 0 hasta 15.
3. Crear la identidad 7x7.
4. Crear un array de 20 elementos y transformarlo en una matriz de 5x4.
5. Crar un array con 20 números con los valores entre 0 y 5 espacioados uniformemente.

In [36]:
x = np.arange(5, 120)
x

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [39]:
x1 = np.arange(16)
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
matriz1 = x1.reshape((4, 4))

In [41]:
matriz1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
identidad = np.ones((7, 7))

In [47]:
identidad

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [48]:
x2 = np.arange(20)
matriz2 = x2.reshape((5, 4))

In [49]:
matriz2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [50]:
lin = np.linspace(0, 5, 20)

In [51]:
lin

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [2]:
len(lin)

NameError: name 'lin' is not defined

**Tareas concluidas**

## Propiedades de los arrays

In [3]:
x = np.arange(12)
x = x.reshape((3, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
x.ndim

2

In [5]:
x.shape

(3, 4)

In [6]:
x.size

12

In [7]:
x.dtype

dtype('int32')

In [8]:
x.itemsize

4

In [9]:
x.data

In [10]:
x[2]

array([ 8,  9, 10, 11])

In [11]:
x[2, 1]

9

In [13]:
x.shape = (4, 3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
y = np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
y[3:8]

array([3, 4, 5, 6, 7])

In [16]:
y[1:7:2]

array([1, 3, 5])

In [17]:
z = np.arange(10, 6, -1)

In [18]:
y[z]

array([10,  9,  8,  7])

In [20]:
x = np.arange(50)
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

## Copias y vistas de arrays

In [21]:
x = np.arange(10)
y = x
y.shape = (2, 5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
y is x

True

In [24]:
z = x.copy()

In [25]:
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
z is x

False

In [27]:
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
t.shape = (5, 2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [29]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
t is x

False

# Funciones universales (ufunc)
- Unarias: sqrt, sin, **2
- Binarias: maximum, minimum

In [31]:
x = np.arange(10)

In [32]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
x-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [35]:
x*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
x/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [37]:
alpha = np.linspace(0, 2*np.pi, 5)
np.sin(alpha)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [38]:
np.cos(alpha)

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16,
        1.0000000e+00])

In [39]:
np.tan(alpha)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16,  5.44374645e+15,
       -2.44929360e-16])

In [40]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [41]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [42]:
np.power(1, x)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [44]:
np.power(3 ,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683], dtype=int32)

In [45]:
np.power(x, 2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [46]:
np.log(x)

<ipython-input-46-de666c833898>:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

Para escribir la función suma hacemos $$\sum_{n=1}^{N} x_n$$

In [48]:
np.sum(x)

45

In [49]:
np.nansum(x)

45

La librería tiene muchísimas funciones muy interesantes que nos ayudan a simplificar más las cuentas y nos hacen más productivos.

In [50]:
notas = [100, 95, 78, 78, 80]

In [51]:
notas1 = np.array(notas)

In [52]:
np.mean(notas1)

86.2

In [53]:
np.std(notas1)

9.389355675444403

In [54]:
np.percentile(notas, q=0.5)

78.0

In [59]:
z = np.random.random((5, 4))

In [61]:
z

array([[0.91023093, 0.60895798, 0.47632759, 0.15992961],
       [0.72242416, 0.63155867, 0.23282786, 0.3965416 ],
       [0.78774268, 0.14414994, 0.44103938, 0.48197257],
       [0.70101179, 0.055439  , 0.33648573, 0.50729887],
       [0.097224  , 0.50178916, 0.08076729, 0.05883379]])

In [60]:
len(z)

5

In [62]:
z.sum()

8.332552609258062

In [64]:
z.sum(axis=0) # Suma por columnas

array([3.21863355, 1.94189476, 1.56744785, 1.60457645])

In [65]:
z.sum(axis=1) # Suma por filas

array([2.15544612, 1.98335229, 1.85490457, 1.6002354 , 0.73861423])